### ISSUE TITLE
Unable to run tests: webdriver timeout

### ISSUE THREAD

**Issue by alvassin** [mulesoft/api-console#279]
Problems with running firefox on mac. Could you please help?

```
$ grunt regression
Running "connect:regression" (connect) task
Started connect web server on http://0.0.0.0:9000

Running "protractor:local" (protractor) task
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://10.250.51.17:4444/wd/hub
ERROR - Unable to start a WebDriver session.

/Users/alvassin/Sites/api-console/node_modules/selenium-webdriver/lib/atoms/error.js:113
  var template = new Error(this.message);
                 ^
UnknownError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
faults":{"e10srollout@mozilla.org":{"d":"/Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi","e":true,"v":"1.0","st":1462240482000},"firefox@getpocket.com":{"d":"/Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi","e":true,"v":"1.0","st":1462240482000},"loop@mozilla.org":{"d":"/Applications/Firefox.app/Contents/Resources/browser/features/loop@mozilla.org.xpi","e":true,"v":"1.2.6","st":1462240482000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","e":true,"v":"46.0.1","st":1462240482000}}}
1464034358767   addons.xpi  DEBUG   No changes found
1464034358773   addons.xpi  DEBUG   Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1464034358773   addons.xpi  DEBUG   Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1464034358784   addons.xpi  DEBUG   Calling bootstrap method startup on e10srollout@mozilla.org version 1.0
1464034358784   addons.xpi  DEBUG   Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1464034358785   addons.xpi  DEBUG   Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1464034358788   addons.xpi  DEBUG   Calling bootstrap method startup on firefox@getpocket.com version 1.0
1464034358795   addons.xpi-utils    DEBUG   Starting async load of XPI database /var/folders/5r/6mpcrd_55t9fm9bs_lm1wl380000gn/T/anonymous7990298762034395099webdriver-profile/extensions.json
1464034358796   addons.xpi  DEBUG   Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/loop@mozilla.org.xpi
1464034358796   addons.xpi  DEBUG   Loading bootstrap scope from /Applications/Firefox.app/Contents/Resources/browser/features/loop@mozilla.org.xpi
1464034358800   addons.xpi  DEBUG   Calling bootstrap method startup on loop@mozilla.org version 1.2.6
1464034358821   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1464034358822   addons.manager  DEBUG   Provider finished startup: XPIProvider
1464034358822   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1464034358822   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1464034358822   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1464034358823   addons.manager  DEBUG   Starting provider: GMPProvider
1464034358827   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1464034358827   addons.manager  DEBUG   Provider finished startup: GMPProvider
1464034358827   addons.manager  DEBUG   Starting provider: PluginProvider
1464034358828   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1464034358828   addons.manager  DEBUG   Provider finished startup: PluginProvider
1464034358828   addons.manager  DEBUG   Completed startup sequence
1464034359076   addons.xpi-utils    DEBUG   Async JSON file read took 0 MS
1464034359076   addons.xpi-utils    DEBUG   Finished async read of XPI database, parsing...
1464034359078   addons.xpi-utils    DEBUG   Successfully read XPI database
1464034359086   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1464034359086   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1464034359087   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1464034359211   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1464034359211   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1464034359211   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
JavaScript warning: https://normandy.cdn.mozilla.net/static/js/bundles/selfrepair-7575f6d27445b45bcffb.js, line 9825: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

    at new bot.Error (/Users/alvassin/Sites/api-console/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
    at Object.bot.response.checkResponse (/Users/alvassin/Sites/api-console/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
    at /Users/alvassin/Sites/api-console/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:152:24
    at /Users/alvassin/Sites/api-console/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/Users/alvassin/Sites/api-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/Users/alvassin/Sites/api-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at notifyAll (/Users/alvassin/Sites/api-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
    at resolve (/Users/alvassin/Sites/api-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
    at fulfill (/Users/alvassin/Sites/api-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:535:5)
    at /Users/alvassin/Sites/api-console/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/Users/alvassin/Sites/api-console/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:149:22)
    at Function.webdriver.WebDriver.createSession (/Users/alvassin/Sites/api-console/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:123:30)
    at Builder.build (/Users/alvassin/Sites/api-console/node_modules/selenium-webdriver/builder.js:294:22)
    at DriverProvider.getNewDriver (/Users/alvassin/Sites/api-console/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at Runner.createBrowser (/Users/alvassin/Sites/api-console/node_modules/protractor/lib/runner.js:180:37)
    at /Users/alvassin/Sites/api-console/node_modules/protractor/lib/runner.js:257:21
    at _fulfilled (/Users/alvassin/Sites/api-console/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/Users/alvassin/Sites/api-console/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/Users/alvassin/Sites/api-console/node_modules/q/q.js:759:13)
[launcher] Process exited with error code 1
```

**Comment by jarrodek** [comment]
API Console version 3 is no longer supported. We are at version 6 right now.
Please, upgrade your version of the console to have latest updates.
