### ISSUE TITLE
include and use directives don't work

### ISSUE THREAD

**Issue by ddidier** [mulesoft/api-console#343]
Hi,
I'm using v3.0.8 and when my main RAML file contains `use:` or `!include` the following error is raised in the browser console and nothing is displayed:

```
api-console-vendor.js:424252
TypeError: Cannot read property 'expand' of null
    at http://localhost:9000/scripts/api-console.js:2788:40
    at Array.forEach (native)
    at http://localhost:9000/scripts/api-console.js:2786:26
    at processQueue (http://localhost:9000/scripts/api-console-vendor.js:425864:27)
    at http://localhost:9000/scripts/api-console-vendor.js:425880:27
    at Scope.$eval (http://localhost:9000/scripts/api-console-vendor.js:427116:28)
    at Scope.$digest (http://localhost:9000/scripts/api-console-vendor.js:426932:31)
    at http://localhost:9000/scripts/api-console-vendor.js:427155:26
    at completeOutstandingRequest (http://localhost:9000/scripts/api-console-vendor.js:417486:10)
    at http://localhost:9000/scripts/api-console-vendor.js:417874:7(anonymous function) @ api-console-vendor.js:424252(anonymous function) @ api-console-vendor.js:421165processQueue @ api-console-vendor.js:425872(anonymous function) @ api-console-vendor.js:425880$eval @ api-console-vendor.js:427116$digest @ api-console-vendor.js:426932(anonymous function) @ api-console-vendor.js:427155completeOutstandingRequest @ api-console-vendor.js:417486(anonymous function) @ api-console-vendor.js:417874

api-console-vendor.js:424252
TypeError: Cannot read property 'buffer' of undefined
    at api-console.js:1117
    at processQueue (api-console-vendor.js:425864)
    at api-console-vendor.js:425880
    at Scope.$eval (api-console-vendor.js:427116)
    at Scope.$digest (api-console-vendor.js:426932)
    at api-console-vendor.js:427155
    at completeOutstandingRequest (api-console-vendor.js:417486)
    at api-console-vendor.js:417874
```

In the developer tools I can see that the included file is correctly fetch.

**Comment by ddidier** [comment]
Any idea? I can't imagine that I the only one seeing this...

**Comment by dacofr** [comment]
Work's for me when i run an http-server who serves
my api.raml and other relative includes files 
and the index.html of api-console.

Hope this help.

**Comment by ddidier** [comment]
Thank you. I finally found out that I forgot the `Library` keyword in one of my header (`#%RAML 1.0 Library`)...
