### ISSUE TITLE
SyntaxError: Invalid regular expression in api-console-vendor.js

### ISSUE THREAD

**Issue by kylios** [mulesoft/api-console#391]
I'm trying to get api-console set up for a service that I run. I downloaded the `3.0.12` release and untarred it in my document root. I've created an `index.html` page based on the example given, and I'm loading it standalone, not in an iframe. So far it looks like this: 

```html
<html>
    <head>
      <link rel="stylesheet" href="/styles/api-console-light-theme.css" type="text/css" />
    </head>
    <body ng-app="ramlConsoleApp" ng-cloak>
      <raml-console-loader src="/api.raml"></raml-console-loader>
      <script type="text/javascript" src="/scripts/api-console-vendor.js"></script>
      <script type="text/javascript" src="/scripts/api-console.js"></script>
      <script type="text/javascript">
        $.noConflict();
      </script>
    </body>
</html>
```

Note that I've told nginx to map `/styles` to `api-console/dist/styles` and `/scripts` to `api-console/dist/scripts`.

When I load the page, all of the script and style assets load correctly, but I get this in my javascript console:

```
api-console-vendor.js:1356 Uncaught SyntaxError: Invalid regular expression: /[\-\.0-9A-Z_a-z\xC0-\xD6\xD8-\xF6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFDÂ·Ì€-Í¯\u203F-â€]/: Range out of order in character class
    at new RegExp (<anonymous>)
    at Object.t.(anonymous function) (http://xxxxxxxxx/scripts/api-console-vendor.js:1356:16756)
    at t (http://xxxxxxxx/scripts/api-console-vendor.js:1288:866)
    at Object.e.exports.code (http://xxxxxxxxx/scripts/api-console-vendor.js:1351:14566)
    at t (http://xxxxxxxx/scripts/api-console-vendor.js:1288:866)
    at Object.<anonymous> (http://xxxxxxxxx/scripts/api-console-vendor.js:1347:15074)
    at Object.<anonymous> (http://xxxxxxxxx/scripts/api-console-vendor.js:1347:22098)
    at t (http://xxxxxxxxx/scripts/api-console-vendor.js:1288:866)
    at Object.t (http://xxxxxxxxx/scripts/api-console-vendor.js:1344:412)
    at t (http://xxxxxxxxx/scripts/api-console-vendor.js:1288:866)
Uncaught SyntaxError: Unexpected identifier
    api-console.js:1007
Uncaught ReferenceError: $ is not defined
    at (index):10
```
(server names are redacted)

I get this error regardless of whether I go through all the steps to run `grunt build` or not. Any help would be appreciated, thanks!

**Comment by kylios** [comment]
Ok, so using the `index.html` from the `dist` directory seems to work better. Perhaps the documentation in your README should be updated to reflect that? (it's out of date in a few places anyway, wrt script names)
