### ISSUE TITLE
Error when using the latest api-console to build

### ISSUE THREAD

**Issue by sachinkshetty** [mulesoft/api-console#649]
i am getting the below error when trying to build using the api-console version 6.0.3 using the below command
api-console build -t "RAML 1.0" -n "6.0.3" resources/contract/raml/api.raml

warn: npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated @hapi/joi@15.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for browserslist@4.13.0: wanted: {"node":"^6 || ^7 || ^8 || ^9 || ^10 || ^11 || ^12 || >=13.7"} (current: {"node":"13.6.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: browserslist@4.13.0

warn: npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

error: 
error: Command failed: node_modules/.bin/rollup -c rollup.config.js
[!] Error: No valid exports main found for '/private/var/folders/1q/t0_rlpvs0yldqr3nzxj7ddj80000gq/T/tmp-72177ArrsP2R2itsd/node_modules/@rollup/pluginutils'
Error: No valid exports main found for '/private/var/folders/1q/t0_rlpvs0yldqr3nzxj7ddj80000gq/T/tmp-72177ArrsP2R2itsd/node_modules/@rollup/pluginutils'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/private/var/folders/1q/t0_rlpvs0yldqr3nzxj7ddj80000gq/T/tmp-72177ArrsP2R2itsd/node_modules/@rollup/plugin-node-resolve/dist/index.js:11:19)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)

any pointers on how to fix the issue

**Comment by jarrodek** [comment]
Hi,

Could you please tell me which version of the CLI tool you are using?
You can get this information by running `api-console --version`.

Thank you

**Comment by sachinkshetty** [comment]
when i run the command api-console --version i get the below error 
Runtime error: Unknown command: undefined

Error: Unknown command: undefined
    at ApiConsoleCli.run (/usr/local/lib/node_modules/api-console-cli/lib/api-console-cli.js:42:13)
    at /usr/local/lib/node_modules/api-console-cli/lib/main.js:11:30
    at Object.<anonymous> (/usr/local/lib/node_modules/api-console-cli/lib/main.js:25:3)
    at Generator.next (<anonymous>)
    at bl (/usr/local/lib/node_modules/api-console-cli/node_modules/esm/esm.js:1:245412)
    at kl (/usr/local/lib/node_modules/api-console-cli/node_modules/esm/esm.js:1:247659)
    at Object.u (/usr/local/lib/node_modules/api-console-cli/node_modules/esm/esm.js:1:287740)
    at Object.o (/usr/local/lib/node_modules/api-console-cli/node_modules/esm/esm.js:1:287137)
    at Object.<anonymous> (/usr/local/lib/node_modules/api-console-cli/node_modules/esm/esm.js:1:284879)
    at Object.apply (/usr/local/lib/node_modules/api-console-cli/node_modules/esm/esm.js:1:199341)

**Comment by sachinkshetty** [comment]
but i had taken in the latest code from the github repo before running npm install on the api-console-cli. i presume( not sure) the cli tool version should be 2.0.3

**Comment by sachinkshetty** [comment]
also if it helps i get few deprecation warning messages before the actual error comes . i have updated my original issue with the warning messages

**Comment by jarrodek** [comment]
If I may ask, how do you use the CLI then? The CLI is designed to be installed in the system as a global command (as a `npm i -g api-console-cli`). By cloning repo you won't get it installed in your system.

The github version is the last version. I am checking your error bu I can't reproduce it so far. I have some other errors though.

**Comment by sachinkshetty** [comment]
i took in the latest code and then ran the command npm i -g api-console-cli

**Comment by jarrodek** [comment]
I just updated the `api-console-cli` module. Try reinstalling the cli tool.

**Comment by sachinkshetty** [comment]
Thanks a lot  @jarrodek  its works
